/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 339d1c20bed54485336ba79b7777a0f8)
interface __BaseEnv_Env {
	AI: Ai;
	ThinkAgent_WorkspaceMonitor: DurableObjectNamespace /* ThinkAgent_WorkspaceMonitor */;
	ThinkAgent_IncidentThread: DurableObjectNamespace /* ThinkAgent_IncidentThread */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
