/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4fe7fc984b6ee74e69a3ab607a0ce6f2)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
	AI: Ai;
	FIRECRAWL_API_URL: "https://api.firecrawl.dev";
	POSTHOG_HOST: string;
	POSTHOG_PROJECT_ID: string;
	POSTHOG_PERSONAL_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	GITHUB_TOKEN: string;
	FIRECRAWL_API_KEY: string;
	ThinkAgent_WorkspaceMonitor: DurableObjectNamespace /* ThinkAgent_WorkspaceMonitor */;
	ThinkAgent_IncidentThread: DurableObjectNamespace /* ThinkAgent_IncidentThread */;
	Sandbox: DurableObjectNamespace<import("./worker").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ThinkAgent_WorkspaceMonitor" | "ThinkAgent_IncidentThread" | "Sandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIRECRAWL_API_URL" | "POSTHOG_HOST" | "POSTHOG_PROJECT_ID" | "POSTHOG_PERSONAL_API_KEY" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN" | "GITHUB_TOKEN" | "FIRECRAWL_API_KEY">> {}
}
