/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: cbb697396bd933622add6d3cd094846e)
interface __BaseEnv_Env {
	AI: Ai;
	POSTHOG_HOST: string;
	POSTHOG_PROJECT_ID: string;
	POSTHOG_PERSONAL_API_KEY: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	ThinkAgent_WorkspaceMonitor: DurableObjectNamespace /* ThinkAgent_WorkspaceMonitor */;
	ThinkAgent_IncidentThread: DurableObjectNamespace /* ThinkAgent_IncidentThread */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "POSTHOG_HOST" | "POSTHOG_PROJECT_ID" | "POSTHOG_PERSONAL_API_KEY" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_API_TOKEN">> {}
}
