// Generated by `think types`. Do not edit this file directly.
// Re-run `think types` after changing Think agents or Wrangler bindings.
// <think-generated>
declare module "virtual:think/entry" {
  const entry: ExportedHandler<Cloudflare.Env>;
  export default entry;
  export const ThinkAgent_IncidentThread: (typeof import("./agents/incident-thread/agent"))["IncidentThread"];
  export const ThinkAgent_WorkspaceMonitor: (typeof import("./agents/workspace-monitor/agent"))["WorkspaceMonitor"];
}
declare module "virtual:think/router" {
  export const thinkRouter: import("@cloudflare/think/server-entry").ThinkRouter;
}

declare namespace Cloudflare {
  interface Env {
    ThinkAgent_IncidentThread: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/incident-thread/agent"))["IncidentThread"]>
    >;
    ThinkAgent_WorkspaceMonitor: DurableObjectNamespace<
      InstanceType<(typeof import("./agents/workspace-monitor/agent"))["WorkspaceMonitor"]>
    >;
  }
}
// </think-generated>
